apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deploy-b
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-b
  minReplicas: 1
  maxReplicas: 9
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20
    scaleUp:
      stabilizationWindowSeconds: 25
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
