apiVersion: v1
kind: Service
metadata:
  name: v2-nginx-ingress
  namespace: v2-nginx-ingress
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: v2-nginx-ingress
